# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_average_number_errors', models.IntegerField(default=0)),
                ('text_minimum_number_errors', models.IntegerField(default=0)),
                ('text_maximum_number_errors', models.IntegerField(default=0)),
                ('lesson_average_speed', models.IntegerField(default=0)),
                ('lesson_maximum_speed', models.IntegerField(default=0)),
                ('lesson_minimum_speed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
